# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8167f6d3a84777c939f48ddf68599cc6b8b713259cbd9756d87caa4d77296d625e425fda9752c45f98e9a56eb6d4e702c2bec59e712cb05b4e3725cab04e9641

test:
  secret_key_base: 11f486d7cf4f922f8411845c586bcb81ab3edc2b885da97db7f7b01706dfe297829303b881699470664a0add90c12ce156bdde7e457f896c60a785590d7fe84b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
