# Profile Information
---
profile:
  :name: The Wanderer
  :about: Oh, well, I'm the type of guy who will never settle down. Where pretty girls are, well, you know that I'm around
  :image_link: profile.jpg
  :profession: Wanderer
  :job_title: CEO
  :company: Wanderer LLC
  :location: Nowhere
  :email: wanderer@wanderer.com
  :languages_spoken: English
