# Social Details Information
---
social_details:
  :facebook: "http://www.facebook.com"
  :twitter: "http://www.twitter.com"
  :linkedin: "http://www.linkedin.com"
  :github: "http://www.github.com"
  :skype_username: The.Wanderer
  :skype_display_name: The Wanderer
