# Work Information
---
works:
  - :name: Personal-Site
    :description: "A personal site capable of being cloned and configured for other users"
    :link: "https://github.com/witZack/personal-site"
